// swift-tools-version:5.9

import PackageDescription

let package = Package(
    name: "notti",
    platforms: [.iOS("17.0")],
    products: [
        .library(name: "notti", targets: ["App"])
    ],
    targets: [
        .target(name: "App", path: "Sources/App")
    ]
)


// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "notti",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "おせっかいアプリ",
            targets: ["AppModule"],
            bundleIdentifier: "ml.mrs1669.notti",
            teamIdentifier: "CKJU28R49D",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sun),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources/AppModule"
        )
    ]
)