name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild build \
                     -project notti.xcodeproj \
                     -scheme notti \
                     -destination 'generic/platform=iOS Simulator'
